# frozen_string_literal: true

brew 'mas'
brew 'git-flow'
brew 'mysql@5.7'
brew 'python@3.8'
brew 'nvm'
# brew "yarn"
brew 'watchman'
brew 'php@7.2'
# zsh is default in MacOS Catalina
# brew "zsh"
brew 'tree'
brew 'openssl'
brew 'rbenv'
brew 'ruby-build'
brew 'postgresql'
brew 'redis'
brew 'forego'
brew 'cmake'
brew 'brotli'
brew 'git-ftp'
brew 'lftp'
brew 'gh'
brew 'gdal'
brew 'lefthook'
brew 'tfenv'
brew 'lcov'

mas 'LINE', id: 539_883_307
mas 'KakaoTalk', id: 869_223_134
mas 'Slack', id: 803_453_959

cask 'ngrok'
tap 'adoptopenjdk/openjdk'
cask 'adoptopenjdk8'
cask 'android-studio'
cask 'sequel-pro'
cask 'db-browser-for-sqlite'
cask 'mysqlworkbench'
cask 'sketch'
cask 'postman'
cask 'sourcetree'
cask 'google-chrome'
cask 'firefox'
cask 'iterm2'
cask 'beyond-compare'
cask 'karabiner-elements'
tap 'heroku/brew'
brew 'heroku/brew/heroku'
cask 'psequel'
cask 'figma'
cask 'github'
cask 'cyberduck'
cask 'flipper'
cask 'clipy'
cask 'macs-fan-control'
