# frozen_string_literal: true

brew 'mas'

brew 'jenv'

brew 'cocoapods'
brew 'git-flow'
brew 'mysql@5.7'
brew 'python@3.8'
brew 'pyenv'
brew 'pipenv'
brew 'pyenv-virtualenv'
brew 'nvm'
brew 'watchman'
tap 'shivammathur/php'
brew 'shivammathur/php/php@7.2', link: true
brew 'composer'
brew 'tree'
brew 'openssl'
brew 'rbenv'
brew 'ruby-build'
brew 'postgresql@14'
brew 'forego'
brew 'brotli'
brew 'git-ftp'
brew 'lftp'
brew 'gh'
brew 'gdal'
brew 'lefthook'
brew 'tfenv'
brew 'lcov'
brew 'go'
brew 'goenv'
brew 'golangci-lint'
brew 'bundletool'
brew 'jq'
brew 'ffmpeg'
brew 'youtube-dl'
brew 'logrotate'

mas 'LINE', id: 539_883_307
mas 'KakaoTalk', id: 869_223_134
mas 'Slack', id: 803_453_959

cask 'ngrok'
cask 'android-studio'
cask 'mysqlworkbench'
cask 'postman'
cask 'google-chrome'
cask 'microsoft-edge'
cask 'firefox'
cask 'iterm2'
cask 'karabiner-elements'
cask 'figma'
cask 'cyberduck'
cask 'clipy'
cask 'framer'
cask 'dbeaver-community'
cask 'visual-studio-code'
cask 'meld'
cask 'docker'
cask 'rectangle'

tap 'leoafarias/fvm'
brew 'fvm'
