# frozen_string_literal: true

brew 'mas'
brew 'git-flow'
brew 'mysql@5.7'
brew 'python@3.8'
brew 'pyenv'
brew 'pipenv'
brew 'pyenv-virtualenv'
brew 'nvm'
# brew "yarn"
brew 'watchman'
brew 'php@7.4'
brew 'composer'
# zsh is default in MacOS Catalina
# brew "zsh"
brew 'tree'
brew 'openssl'
brew 'rbenv'
brew 'ruby-build'
brew 'postgresql'
brew 'redis'
brew 'forego'
brew 'cmake'
brew 'brotli'
brew 'git-ftp'
brew 'lftp'
brew 'gh'
brew 'gdal'
brew 'lefthook'
brew 'tfenv'
brew 'lcov'
brew 'go'
brew 'golangci-lint'
brew 'bundletool'

mas 'LINE', id: 539_883_307
mas 'KakaoTalk', id: 869_223_134
mas 'Slack', id: 803_453_959

cask 'ngrok'
tap 'adoptopenjdk/openjdk'
cask 'adoptopenjdk11'
cask 'android-studio'
cask 'mysqlworkbench'
cask 'postman'
cask 'google-chrome'
cask 'firefox'
cask 'iterm2'
cask 'karabiner-elements'
tap 'heroku/brew'
brew 'heroku/brew/heroku'
cask 'figma'
cask 'cyberduck'
cask 'clipy'
cask 'macs-fan-control'
cask 'pgadmin4'
cask 'google-cloud-sdk'
cask 'nosql-workbench'
cask 'local'
cask 'framer'
cask 'dbeaver-community'
tap 'mongodb/brew'
brew 'mongodb-community'
cask 'visual-studio-code'
cask 'meld'
cask 'docker'